--- #YAML:1.0
name:                Email-FolderType-Net
version:             1.041
abstract:            recognize folder types for network based message protocols
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::FolderType:             0.8
    Test::More:                    0.47
    URI:                           1.35
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
