# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-FolderType-Net
version:      1.01
version_from: lib/Email/FolderType/Net.pm
installdirs:  site
requires:
    Email::LocalDelivery::Register: 
    Test::More:                    0.47
    URI:                           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
